const TRANSACTION_TYPES = {
  BET: 'BET',
  WIN: 'WIN',
  LOSE: 'LOSE',
  REFUND: 'REFUND',
}

const GAME_TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  LOSE: 'LOSE',
}

enum GAME_CATEGORIES {
  SLOTS = 'Slots',
  LIVE_CASINO = 'Live Casino',
  CRASH = 'Crash',
}

export { GAME_CATEGORIES, GAME_TRANSACTION_STATUS, TRANSACTION_TYPES }
